// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#include "../ui.h"

void ui_menu_screen_init(void)
{
    ui_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menu, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_volumn = lv_slider_create(ui_menu);
    lv_slider_set_value(ui_volumn, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volumn) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volumn, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_volumn, 140);
    lv_obj_set_height(ui_volumn, 15);
    lv_obj_set_x(ui_volumn, 0);
    lv_obj_set_y(ui_volumn, 20);
    lv_obj_set_align(ui_volumn, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_volumn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags


    ui_sliderLabel = lv_label_create(ui_menu);
    lv_obj_set_width(ui_sliderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sliderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sliderLabel, 0);
    lv_obj_set_y(ui_sliderLabel, 45);
    lv_obj_set_align(ui_sliderLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_sliderLabel, "Volumn 80");
    lv_obj_clear_flag(ui_sliderLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_wakeButton = lv_btn_create(ui_menu);
    lv_obj_set_width(ui_wakeButton, 100);
    lv_obj_set_height(ui_wakeButton, 50);
    lv_obj_set_x(ui_wakeButton, 0);
    lv_obj_set_y(ui_wakeButton, 80);
    lv_obj_set_align(ui_wakeButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_wakeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wakeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_wakeLabel = lv_label_create(ui_menu);
    lv_obj_set_width(ui_wakeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wakeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wakeLabel, -2);
    lv_obj_set_y(ui_wakeLabel, -56);
    lv_obj_set_align(ui_wakeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wakeLabel, "send");
    lv_obj_clear_flag(ui_wakeLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_delNetSetButton = lv_btn_create(ui_menu);
    lv_obj_set_width(ui_delNetSetButton, 100);
    lv_obj_set_height(ui_delNetSetButton, 50);
    lv_obj_set_x(ui_delNetSetButton, 0);
    lv_obj_set_y(ui_delNetSetButton, 150);
    lv_obj_set_align(ui_delNetSetButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_delNetSetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_delNetSetButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_delNetSetLabel = lv_label_create(ui_menu);
    lv_obj_set_width(ui_delNetSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delNetSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_delNetSetLabel, -3);
    lv_obj_set_y(ui_delNetSetLabel, 14);
    lv_obj_set_align(ui_delNetSetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delNetSetLabel, "delNetSet");
    lv_obj_clear_flag(ui_delNetSetLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_add_event_cb(ui_volumn, ui_event_volumn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wakeButton, ui_event_wakeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_delNetSetButton, ui_event_delNetSetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menu, ui_event_menu, LV_EVENT_ALL, NULL);

}
