// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_container1 = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_container1);
    lv_obj_set_width(ui_container1, 320);
    lv_obj_set_height(ui_container1, 240);
    lv_obj_set_align(ui_container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_status = lv_obj_create(ui_container1);
    lv_obj_remove_style_all(ui_status);
    lv_obj_set_width(ui_status, 320);
    lv_obj_set_height(ui_status, 36);
    lv_obj_clear_flag(ui_status, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_status, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_status, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(ui_status, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_status, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_status, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_status, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_changeBar = lv_bar_create(ui_status);
    lv_bar_set_value(ui_changeBar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_changeBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_changeBar, 41);
    lv_obj_set_height(ui_changeBar, 14);
    lv_obj_set_x(ui_changeBar, -5);
    lv_obj_set_y(ui_changeBar, 9);
    lv_obj_set_align(ui_changeBar, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_changeBar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_changeBar, lv_color_hex(0xF7024A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_changeBar, lv_color_hex(0xF7021E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_changeBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_notificationLabel = lv_label_create(ui_status);
    lv_obj_set_width(ui_notificationLabel, 136);
    lv_obj_set_height(ui_notificationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notificationLabel, -18);
    lv_obj_set_y(ui_notificationLabel, 0);
    lv_obj_set_align(ui_notificationLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_notificationLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_notificationLabel, "notify");
    lv_obj_clear_flag(ui_notificationLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_align(ui_notificationLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_netLabel = lv_label_create(ui_status);
    lv_obj_set_width(ui_netLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netLabel, 10);
    lv_obj_set_y(ui_netLabel, 10);
    lv_label_set_text(ui_netLabel, "");
    lv_obj_set_style_text_font(ui_netLabel, &ui_font_iconFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volLabel2 = lv_label_create(ui_status);
    lv_obj_set_width(ui_volLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volLabel2, -50);
    lv_obj_set_y(ui_volLabel2, 10);
    lv_obj_set_align(ui_volLabel2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_volLabel2, "");
    lv_obj_set_style_text_align(ui_volLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volLabel2, &ui_font_iconFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Content = lv_obj_create(ui_container1);
    lv_obj_remove_style_all(ui_Content);
    lv_obj_set_width(ui_Content, 320);
    lv_obj_set_height(ui_Content, 204);
    lv_obj_set_x(ui_Content, 0);
    lv_obj_set_y(ui_Content, 36);
    lv_obj_clear_flag(ui_Content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Content, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AITextArea = lv_textarea_create(ui_Content);
    lv_obj_set_width(ui_AITextArea, 280);
    lv_obj_set_height(ui_AITextArea, 75);
    lv_obj_set_x(ui_AITextArea, 10);
    lv_obj_set_y(ui_AITextArea, 10);
    lv_textarea_set_max_length(ui_AITextArea, 1000);
    lv_textarea_set_placeholder_text(ui_AITextArea, "AI...");
    lv_obj_clear_flag(ui_AITextArea, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags



    ui_userTextArea = lv_textarea_create(ui_Content);
    lv_obj_set_width(ui_userTextArea, 280);
    lv_obj_set_height(ui_userTextArea, 75);
    lv_obj_set_x(ui_userTextArea, 30);
    lv_obj_set_y(ui_userTextArea, 45);
    lv_obj_set_align(ui_userTextArea, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_userTextArea, 1000);
    lv_textarea_set_placeholder_text(ui_userTextArea, "user...");
    lv_obj_clear_flag(ui_userTextArea, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags



    lv_obj_add_event_cb(ui_changeBar, ui_event_changeBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AITextArea, ui_event_AITextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_userTextArea, ui_event_userTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);

}
