// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main(lv_event_t * e);
lv_obj_t * ui_main;
lv_obj_t * ui_container1;
lv_obj_t * ui_status;
void ui_event_changeBar(lv_event_t * e);
lv_obj_t * ui_changeBar;
lv_obj_t * ui_notificationLabel;
lv_obj_t * ui_netLabel;
lv_obj_t * ui_volLabel2;
lv_obj_t * ui_Content;
void ui_event_AITextArea(lv_event_t * e);
lv_obj_t * ui_AITextArea;
lv_obj_t * ui_emotionlabel;
void ui_event_userTextArea(lv_event_t * e);
lv_obj_t * ui_userTextArea;
// CUSTOM VARIABLES


// SCREEN: ui_QRcode
void ui_QRcode_screen_init(void);
lv_obj_t * ui_QRcode;
lv_obj_t * ui_QRcodeImg;
lv_obj_t * ui_QRcodeLabel;
// CUSTOM VARIABLES


// SCREEN: ui_menu
void ui_menu_screen_init(void);
void ui_event_menu(lv_event_t * e);
lv_obj_t * ui_menu;
void ui_event_volumn(lv_event_t * e);
lv_obj_t * ui_volumn;
lv_obj_t * ui_sliderLabel;
void ui_event_wakeButton(lv_event_t * e);
lv_obj_t * ui_wakeButton;
lv_obj_t * ui_wakeLabel;
void ui_event_delNetSetButton(lv_event_t * e);
lv_obj_t * ui_delNetSetButton;
lv_obj_t * ui_delNetSetLabel;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_logo[1] = {&ui_img_logo1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_menu_screen_init);
    }
}

void ui_event_changeBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        checkBatColor(e);
    }
}

void ui_event_AITextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_menu_screen_init);
    }
}

void ui_event_userTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
    }
}

void ui_event_menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
    }
}

void ui_event_volumn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeVolumn(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_sliderLabel, target, "Volumn ", "");
    }
}

void ui_event_wakeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        ClickeWake(e);
    }
}

void ui_event_delNetSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        ClickeDelNetSet(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui_QRcode_screen_init();
    ui_menu_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
