// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#ifndef _SQUARELINE_TEST1_UI_H
#define _SQUARELINE_TEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main(lv_event_t * e);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_container1;
extern lv_obj_t * ui_status;
void ui_event_changeBar(lv_event_t * e);
extern lv_obj_t * ui_changeBar;
extern lv_obj_t * ui_notificationLabel;
extern lv_obj_t * ui_netLabel;
extern lv_obj_t * ui_volLabel2;
extern lv_obj_t * ui_Content;
void ui_event_AITextArea(lv_event_t * e);
extern lv_obj_t * ui_AITextArea;
extern lv_obj_t * ui_emotionlabel;
void ui_event_userTextArea(lv_event_t * e);
extern lv_obj_t * ui_userTextArea;
// CUSTOM VARIABLES

// SCREEN: ui_QRcode
void ui_QRcode_screen_init(void);
extern lv_obj_t * ui_QRcode;
extern lv_obj_t * ui_QRcodeImg;
extern lv_obj_t * ui_QRcodeLabel;
// CUSTOM VARIABLES

// SCREEN: ui_menu
void ui_menu_screen_init(void);
void ui_event_menu(lv_event_t * e);
extern lv_obj_t * ui_menu;
void ui_event_volumn(lv_event_t * e);
extern lv_obj_t * ui_volumn;
extern lv_obj_t * ui_sliderLabel;
void ui_event_wakeButton(lv_event_t * e);
extern lv_obj_t * ui_wakeButton;
extern lv_obj_t * ui_wakeLabel;
void ui_event_delNetSetButton(lv_event_t * e);
extern lv_obj_t * ui_delNetSetButton;
extern lv_obj_t * ui_delNetSetLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_download_png);    // assets/download.png
LV_IMG_DECLARE(ui_img_logo1_png);    // assets/logo1.png

// FONTS
LV_FONT_DECLARE(ui_font_iconFont);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
