// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_test1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void checkBatColor(lv_event_t * e);
void ChangeVolumn(lv_event_t * e);
void ClickeWake(lv_event_t * e);
void ClickeDelNetSet(lv_event_t * e);

void ChangeVolumn_cc(int volum);
void send_data_cc();
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
